fatal: ambiguous argument 'feature\rust-libsql-update;.github\workflows\ci.yml': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
